# Generated by Django 3.2.25 on 2024-08-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_interval', models.IntegerField(default=3)),
            ],
        ),
    ]
