# Generated by Django 3.2.25 on 2024-08-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
